-- 011_commercial_and_finance.sql
-- Commercial Engine, Contracts, Fee Rules, Fee Events, Immutable Financial Ledger, Billing, Invoices, Payments, Settlements, Credits

CREATE SCHEMA IF NOT EXISTS commercial;
CREATE SCHEMA IF NOT EXISTS finance;

-- 1. Commercial SaaS Plans
CREATE TABLE IF NOT EXISTS commercial.plans (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(150) NOT NULL,
    code VARCHAR(50) NOT NULL UNIQUE,
    description TEXT,
    billing_interval VARCHAR(20) NOT NULL DEFAULT 'MONTHLY' CHECK (billing_interval IN ('MONTHLY', 'QUARTERLY', 'ANNUAL')),
    price NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    currency VARCHAR(3) NOT NULL DEFAULT 'ETB',
    limits JSONB NOT NULL DEFAULT '{"maxListings": 50, "maxUsers": 5, "maxDomains": 1, "leadCredits": 20}'::jsonb,
    features JSONB NOT NULL DEFAULT '["INVENTORY", "CRM", "BASIC_ANALYTICS"]'::jsonb,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2. Partner Commercial Contracts
CREATE TABLE IF NOT EXISTS commercial.contracts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES organizations.tenants(id) ON DELETE CASCADE,
    plan_id UUID REFERENCES commercial.plans(id) ON DELETE RESTRICT,
    contract_number VARCHAR(100) NOT NULL UNIQUE,
    version INTEGER NOT NULL DEFAULT 1,
    status VARCHAR(50) NOT NULL DEFAULT 'DRAFT' CHECK (status IN (
        'DRAFT', 'PENDING_APPROVAL', 'ACTIVE', 'EXPIRED', 'TERMINATED', 'DISPUTED'
    )),
    effective_date DATE NOT NULL,
    expiry_date DATE,
    fee_model VARCHAR(50) NOT NULL DEFAULT 'HYBRID' CHECK (fee_model IN (
        'SUBSCRIPTION', 'LISTING_FEE', 'LEAD_FEE', 'SUCCESS_DEAL', 'SALES_AGENT_COMMISSION', 'HYBRID', 'CUSTOM'
    )),
    terms JSONB NOT NULL DEFAULT '{}'::jsonb, -- waterfall shares, tax, payment cycles, exclusivity
    signed_document_url TEXT,
    approved_by UUID REFERENCES identity.users(id) ON DELETE SET NULL,
    approved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_contracts_org ON commercial.contracts(organization_id);

CREATE TRIGGER update_contracts_updated_at
    BEFORE UPDATE ON commercial.contracts
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 3. Contract Versions (Immutable Historical Rules)
CREATE TABLE IF NOT EXISTS commercial.contract_versions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contract_id UUID NOT NULL REFERENCES commercial.contracts(id) ON DELETE CASCADE,
    version_number INTEGER NOT NULL,
    terms JSONB NOT NULL,
    effective_from TIMESTAMPTZ NOT NULL,
    effective_to TIMESTAMPTZ,
    created_by UUID REFERENCES identity.users(id) ON DELETE SET NULL,
    change_reason TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_contract_version UNIQUE (contract_id, version_number)
);

-- 4. Fee & Commission Rules
CREATE TABLE IF NOT EXISTS commercial.fee_rules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contract_id UUID REFERENCES commercial.contracts(id) ON DELETE CASCADE,
    domain_id UUID REFERENCES domains.domains(id) ON DELETE CASCADE,
    category_id UUID REFERENCES domains.categories(id) ON DELETE CASCADE,
    fee_type VARCHAR(50) NOT NULL CHECK (fee_type IN (
        'SUBSCRIPTION', 'LISTING', 'QUALIFIED_LEAD', 'APPOINTMENT', 'SUCCESS_COMMISSION', 'AGENT_COMMISSION'
    )),
    calculation_type VARCHAR(50) NOT NULL CHECK (calculation_type IN ('FIXED', 'PERCENTAGE', 'TIERED')),
    rate_value NUMERIC(10, 4) NOT NULL, -- e.g. 2.5000 for 2.5% or 500.00 for fixed fee
    min_amount NUMERIC(15, 2),
    max_amount NUMERIC(15, 2),
    currency VARCHAR(3) NOT NULL DEFAULT 'ETB',
    trigger_event VARCHAR(100) NOT NULL, -- 'lead.qualified', 'appointment.completed', 'deal.closed', 'subscription.renewal'
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 5. Fee Events (Generated by Business Triggers)
CREATE TABLE IF NOT EXISTS commercial.fee_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES organizations.tenants(id) ON DELETE CASCADE,
    contract_id UUID NOT NULL REFERENCES commercial.contracts(id) ON DELETE RESTRICT,
    contract_version INTEGER NOT NULL DEFAULT 1,
    fee_rule_id UUID REFERENCES commercial.fee_rules(id) ON DELETE SET NULL,
    listing_id UUID REFERENCES inventory.listings(id) ON DELETE SET NULL,
    lead_id UUID REFERENCES crm.leads(id) ON DELETE SET NULL,
    deal_id UUID REFERENCES sales.deals(id) ON DELETE SET NULL,
    agent_id UUID REFERENCES identity.users(id) ON DELETE SET NULL,
    trigger_event VARCHAR(100) NOT NULL,
    calculation_basis NUMERIC(15, 2) NOT NULL, -- e.g. gross transaction value
    calculated_amount NUMERIC(15, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'ETB',
    status VARCHAR(50) NOT NULL DEFAULT 'ESTIMATED' CHECK (status IN (
        'ESTIMATED', 'PENDING', 'EARNED', 'INVOICED', 'PAYABLE', 'PAID', 'DISPUTED', 'REVERSED'
    )),
    idempotency_key VARCHAR(150) UNIQUE,
    notes TEXT,
    earned_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_fee_events_org ON commercial.fee_events(organization_id);
CREATE INDEX IF NOT EXISTS idx_fee_events_deal ON commercial.fee_events(deal_id);
CREATE INDEX IF NOT EXISTS idx_fee_events_status ON commercial.fee_events(status);

-- 6. Commercial Disputes & Fee Holds
CREATE TABLE IF NOT EXISTS commercial.disputes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES organizations.tenants(id) ON DELETE CASCADE,
    fee_event_id UUID NOT NULL REFERENCES commercial.fee_events(id) ON DELETE CASCADE,
    reason TEXT NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'OPENED' CHECK (status IN (
        'OPENED', 'UNDER_REVIEW', 'ACCEPTED', 'REJECTED', 'ADJUSTED', 'CLOSED'
    )),
    requested_adjustment NUMERIC(15, 2),
    resolution_notes TEXT,
    resolved_by UUID REFERENCES identity.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 7. Financial Ledger (Double-Entry Source of Truth with Immutability Protection)
CREATE TABLE IF NOT EXISTS finance.financial_ledger (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES organizations.tenants(id) ON DELETE CASCADE,
    contract_id UUID REFERENCES commercial.contracts(id) ON DELETE SET NULL,
    deal_id UUID REFERENCES sales.deals(id) ON DELETE SET NULL,
    fee_event_id UUID REFERENCES commercial.fee_events(id) ON DELETE SET NULL,
    entry_type VARCHAR(50) NOT NULL CHECK (entry_type IN (
        'PLATFORM_FEE', 'AGENT_COMMISSION', 'PARTNER_PAYOUT', 'SUBSCRIPTION_FEE', 'ADJUSTMENT', 'CLAWBACK', 'CREDIT_PURCHASE'
    )),
    debit_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    credit_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    currency VARCHAR(3) NOT NULL DEFAULT 'ETB',
    balance_after NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    reference_number VARCHAR(100) NOT NULL,
    notes TEXT,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ledger_org ON finance.financial_ledger(organization_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ledger_fee_event ON finance.financial_ledger(fee_event_id);

-- Enforce append-only ledger immutability
CREATE OR REPLACE FUNCTION finance.prevent_ledger_modification()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'Financial ledger entries are immutable. UPDATE and DELETE operations are strictly prohibited.';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER enforce_ledger_immutability
    BEFORE UPDATE OR DELETE ON finance.financial_ledger
    FOR EACH ROW
    EXECUTE FUNCTION finance.prevent_ledger_modification();

-- 8. Invoices
CREATE TABLE IF NOT EXISTS finance.invoices (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES organizations.tenants(id) ON DELETE CASCADE,
    invoice_number VARCHAR(100) NOT NULL UNIQUE,
    type VARCHAR(50) NOT NULL DEFAULT 'COMMISSION' CHECK (type IN (
        'SUBSCRIPTION', 'USAGE_LEAD', 'COMMISSION', 'CREDIT_PURCHASE'
    )),
    subtotal NUMERIC(15, 2) NOT NULL,
    tax_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    total_amount NUMERIC(15, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'ETB',
    status VARCHAR(50) NOT NULL DEFAULT 'ISSUED' CHECK (status IN (
        'DRAFT', 'ISSUED', 'PAID', 'PARTIALLY_PAID', 'OVERDUE', 'CANCELLED', 'REFUNDED'
    )),
    due_date DATE NOT NULL,
    issued_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    paid_at TIMESTAMPTZ,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_invoices_org ON finance.invoices(organization_id);

-- 9. Invoice Line Items
CREATE TABLE IF NOT EXISTS finance.invoice_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    invoice_id UUID NOT NULL REFERENCES finance.invoices(id) ON DELETE CASCADE,
    fee_event_id UUID REFERENCES commercial.fee_events(id) ON DELETE SET NULL,
    description VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    unit_price NUMERIC(15, 2) NOT NULL,
    total_amount NUMERIC(15, 2) NOT NULL
);

-- 10. Payments & Reconciliation
CREATE TABLE IF NOT EXISTS finance.payments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES organizations.tenants(id) ON DELETE CASCADE,
    invoice_id UUID REFERENCES finance.invoices(id) ON DELETE SET NULL,
    amount NUMERIC(15, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'ETB',
    payment_method VARCHAR(50) NOT NULL CHECK (payment_method IN (
        'BANK_TRANSFER', 'TELEBIRR', 'CBE_BIRR', 'STRIPE', 'CASH', 'CREDIT_BALANCE'
    )),
    status VARCHAR(50) NOT NULL DEFAULT 'COMPLETED' CHECK (status IN (
        'PENDING', 'COMPLETED', 'FAILED', 'REVERSED'
    )),
    reference_number VARCHAR(100) NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_payments_invoice ON finance.payments(invoice_id);

-- 11. Partner Settlement Statements
CREATE TABLE IF NOT EXISTS finance.settlements (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES organizations.tenants(id) ON DELETE CASCADE,
    statement_number VARCHAR(100) NOT NULL UNIQUE,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    total_gross_sales NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    total_platform_fees NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    total_agent_commissions NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    net_payable_to_partner NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'PAID')),
    settled_at TIMESTAMPTZ,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_settlements_org ON finance.settlements(organization_id);

-- 12. Credits Ledger (Prepaid lead and listing credits)
CREATE TABLE IF NOT EXISTS finance.credits (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES organizations.tenants(id) ON DELETE CASCADE,
    credit_type VARCHAR(50) NOT NULL CHECK (credit_type IN (
        'LEAD_CREDITS', 'FEATURED_LISTING', 'ADVERTISING', 'API_USAGE', 'STORAGE'
    )),
    balance INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_credit_org_type UNIQUE (organization_id, credit_type)
);

CREATE TABLE IF NOT EXISTS finance.credit_transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    credit_id UUID NOT NULL REFERENCES finance.credits(id) ON DELETE CASCADE,
    amount INTEGER NOT NULL, -- positive for purchase/grant, negative for deduction
    balance_after INTEGER NOT NULL,
    type VARCHAR(50) NOT NULL CHECK (type IN ('PURCHASE', 'GRANT', 'DEDUCTION', 'EXPIRY', 'REFUND')),
    reference_id VARCHAR(100),
    reason TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
